<?php
/**
 * @file
 * The module.
 */

/**
 * We do require this.
 */
require_once __DIR__ . '/filechunk.element.inc';

/**
 * And this too.
 */
require_once __DIR__ . '/filechunk.field.inc';

/**
 * Implements hook_menu().
 */
function filechunk_menu() {
  $items = [];
  $items['system/chunk-upload'] = [
    'page callback'     => 'filechunk_upload_callback',
    'access callback'   => 'filechunk_upload_access',
    'type'              => MENU_CALLBACK,
    'file'              => 'filechunk.ajax.inc',
  ];
  $items['system/chunk-remove'] = [
    'page callback'     => 'filechunk_remove_callback',
    'access callback'   => 'filechunk_remove_access',
    'type'              => MENU_CALLBACK,
    'file'              => 'filechunk.ajax.inc',
  ];
  return $items;
}

/**
 * Implements hook_admin_paths().
 */
function filechunk_admin_paths() {
  return [
    'system/chunk-upload/test' => true,
    'system/chunk-upload/test/*' => true,
  ];
}

/**
 * Implements hook_theme().
 */
function filechunk_theme() {
  return [
    'filechunk_file_input' => [
      'render element' => 'element',
    ],
  ];
}

/**
 * Implements hook_library().
 */
function filechunk_library() {
  return [
    'widget' => [
      'title' => "Chunked file widget",
      'version' => '1.0',
      'js' => [drupal_get_path('module', 'filechunk') . '/filechunk.js' => []],
      'css' => [drupal_get_path('module', 'filechunk') . '/filechunk.css' => []],
    ],
  ];
}

/**
 * Get upload directory.
 *
 * @return string
 */
function filechunk_upload_dir_get() {
  // return variable_get('filechunk_upload_directory', "temporary://filechunk") . '/';
  return "temporary://filechunk/";
}

/**
 * Render file preview for the widget element.
 *
 * @param stdClass $file
 *
 * @return mixed
 *   drupal_render() friendly structure.
 */
function filechunk_element_file_display($file) {
  return ['#theme' => 'file_link', '#file' => $file];
}

/**
 * Parse content range header.
 *
 * @param string $contentRange
 */
function filechunk_parse_range($contentRange) {
  $matches = [];
  if (!preg_match('@^bytes (\d+)-(\d+)/(\d+)$@', trim($contentRange), $matches)) {
    return false;
  }
  list(, $start, $stop, $filesize) = $matches;
  if ($filesize < $start) {
    return false; // Invalid request.
  }
  if ($filesize < $stop) {
    return false; // Invalid request.
  }
  if ($stop < $start) {
    return false; // Invalid request.
  }
  if ($start === $stop) {
    return false; // Cannot import '0' sized file.
  }
  return [$start, $stop, $filesize];
}

/**
 * Menu access callback.
 */
function filechunk_remove_access() {
  if ('POST' !== $_SERVER['REQUEST_METHOD']) {
    return false;
  }
  if (empty($_SERVER['HTTP_X_FILE_ID'])) {
    return false;
  }
  if (empty($_SERVER['HTTP_X_FILE_TOKEN']) || !drupal_valid_token($_SERVER['HTTP_X_FILE_TOKEN'])) {
    return false;
  }
  return true;
}

/**
 * Menu access callback.
 */
function filechunk_upload_access() {
  if ('POST' !== $_SERVER['REQUEST_METHOD']) {
    return false;
  }
  if (empty($_SERVER['HTTP_X_FILE_NAME'])) {
    return false;
  }
  if (empty($_SERVER['HTTP_CONTENT_RANGE']) || !filechunk_parse_range($_SERVER['HTTP_CONTENT_RANGE'])) {
    return false;
  }
  if (empty($_SERVER['HTTP_X_FILE_TOKEN']) || !drupal_valid_token($_SERVER['HTTP_X_FILE_TOKEN'])) {
    return false;
  }
  return true;
}
